### ISSUE TITLE
[Overlay] Failing to use overlay running games in WINE (umu ge-proton) on Linux

### ISSUE THREAD

**Issue by puyebu** [Detanup01/gbe_fork#97]
I have been attempting to use overlay for a while to no success. I remember it working at some point long ago but currently it doesn't for some reason.
I don't see any errors or any reaction from the overlay which is why I don't understand why it is not working.
I am using ColdLoader on WarmSnow in this case:

<details>
<summary>Log</summary>

```
[0 ms, 95 us] Searching for configuration file: Z:\mnt\Games\WarmSnow\steamclient_loader_x64.ini
[0 ms, 488 us] Searching for configuration file: Z:\mnt\Games\WarmSnow\ColdClientLoader.ini
[0 ms, 771 us] result of parsing ini 'Z:\mnt\Games\WarmSnow\ColdClientLoader.ini' 0 (success == 0)
[0 ms, 834 us] SteamClient::Exe: Z:\mnt\Games\WarmSnow\WarmSnow.exe
[0 ms, 878 us] SteamClient::ExeRunDir: 
[0 ms, 918 us] SteamClient::ExeCommandLine: 
[0 ms, 959 us] SteamClient::AppId: 1296830
[0 ms, 999 us] SteamClient::SteamClient: Z:\mnt\Games\WarmSnow\steamclient.dll
[1 ms, 1040 us] SteamClient::SteamClient64Dll: Z:\mnt\Games\WarmSnow\steamclient64.dll
[1 ms, 1081 us] SteamClient::PersistentMode: 0
[1 ms, 1122 us] SteamClient::ForceInjectSteamClient: 1
[1 ms, 1162 us] SteamClient::ForceInjectGameOverlayRenderer: 1
[1 ms, 1202 us] Injection::DllsToInjectFolder: 
[1 ms, 1243 us] Injection::IgnoreInjectionError: 1
[1 ms, 1283 us] Injection::IgnoreLoaderArchDifference: 0
[1 ms, 1324 us] Debug::ResumeByDebugger: 0
[1 ms, 1537 us] Setting ExeRunDir to: Z:\mnt\Games\WarmSnow
[2 ms, 2533 us] Detected exe arch: x64
[2 ms, 2584 us] Detected loader arch: x64
[2 ms, 2887 us] Found previous registry entry (HKCU) for Steam
[3 ms, 3030 us] Found previous registry entry (HKCU #2) for Steam
[3 ms, 3163 us] Found previous registry entry (HKLM) for Steam
[3 ms, 3268 us] Found previous registry entry (HKCS) #1 for Steam
[3 ms, 3330 us] Found previous registry entry (HKCS) #2 for Steam
[3 ms, 3418 us] spawning the requested EXE file
[17 ms, 17698 us] injecting 2 dlls
[17 ms, 17792 us] Injecting dll: 'Z:\mnt\Games\WarmSnow\steamclient64.dll' ...
[80 ms, 80164 us] Injected!
[80 ms, 80262 us] Injecting dll: 'Z:\mnt\Games\WarmSnow\GameOverlayRenderer64.dll' ...
[82 ms, 82133 us] Injected!
[82 ms, 82215 us] resuming the main thread of the exe
[17121 ms, 17121741 us] restoring registry entries (HKCU)
[17121 ms, 17121983 us] restoring registry entries (HKCU #2)
[17122 ms, 17122107 us] restoring registry entries (HKLM)
[17122 ms, 17122217 us] restoring registry entries (HKCS) #2
[17122 ms, 17122315 us] restoring registry entries (HKCS) #1
```
</details>

**Comment by Edremon** [comment]
Are you using a build newer than 995414e? As far as I'm aware, all dxvk issues were fixed in ingame_overlay and thus fixed in this emulator when the dependency was updated.

**Comment by puyebu** [comment]
Last build I tried is [Release 2024 11 24 Experimental](https://github.com/Detanup01/gbe_fork/releases/tag/release-2024_11_24_exp)

**Comment by alex47exe** [comment]
Might not fix your issue, but try to use my release, which includes an updated ingame_overlay, 3 commits ahead of the one in Detanup01's release.
[https://github.com/alex47exe/gse_fork/releases](https://github.com/alex47exe/gse_fork/releases)

**Comment by puyebu** [comment]
I checked but it doesn't work.
I do not see anything related to overlay in logs, does it even work with ColdClientLoader?
It is triggered by shift-tab, right?

**Comment by ndiruhniu** [comment]
I just checked [this](https://github.com/Detanup01/gbe_fork/releases/tag/release-2024_11_24_exp) version in the standard way and via ColdLoader, everything works:
![pic1](https://github.com/user-attachments/assets/7637ebc5-1302-493d-946b-4c129b0c4f95)
tested on wine-ge 8.26/wine 9.21 and dxvk 2.5.1

maybe you forgot to enable overlay in configs.overlay.ini?

**Comment by puyebu** [comment]
So I have checked, the latest one works with with does work wine-ge 8.26 but doesn't work with [umu-run ge-proton](https://github.com/Open-Wine-Components/umu-launcher), which makes some games run better for me and is supposed to be the next thing after wine-ge, which has stopped updating.
Edited title to clarify the issue.
I am not sure what the issue could be, from the logs it is injected just fine?

**Comment by Edremon** [comment]
Doesn't Proton does a lot of fuckery to basically bridge all steam call to linux side? I never used it, so my knowledge about that is limited. From a quick look at code, it hijack dll loading code and could be disabled by setting PROTON_DISABLE_LSTEAMCLIENT 1. https://github.com/ValveSoftware/wine/blob/488fb296dda334a1e8555a9dd8f5cbe09be2afe5/dlls/ntdll/loader.c#L2294

Anyway the log that you posted is just stdout/stderr of the cold client loader, if you want to debug that further, you need a debug build of the emulator and read/post content of STEAM_LOG file. If you want to debug overlay even further, you need to build overlay dep with `INGAMEOVERLAY_USE_SPDLOG=ON`.

**Comment by puyebu** [comment]
`PROTON_DISABLE_LSTEAMCLIENT=1` made the overlay work. 
Might worth mentioning this in the readme.
Seems like achievements were not working as when I checked there were no folders in GSE_SAVES. Which is weird, as I understood it should be working if games use emu. And games do work and not complain about not having steam, which is weird.
Thank you for the troubles, I looked at the docs and didn't find that specific setting.
